project_name: cmt
dist: .bin
builds:
  - id: cmt
    binary: "cmt"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    dir: cmd
    main: ./main.go
    ldflags: "-s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"

archives:
  - id: cmt
    name_template: >-
      {{.ProjectName}}_
      {{- .Tag}}_
      {{- if eq .Os "darwin"}}macos
      {{- else if eq .Os "windows"}}win
      {{- else}}{{.Os}}{{end}}_
      {{- if eq .Arch "amd64"}}x86_64
      {{- else if eq .Arch "386"}}i386
      {{- else}}{{.Arch}}{{end}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
